name: Docker

on:
  schedule:
    - cron: '33 2 * * *'
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write
  id-token: write
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: eximpe/action-runner


jobs:
  release:
    name: Release and build on Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessary to fetch all tags

      - name: Calculate next tag
        id: calc_tag
        run: |
          YEAR=$(date +"%y")
          WEEK=$(date +"%V")
          LAST_TAG=$(git tag -l "v$YEAR.$WEEK.*" | sort -V | tail -n1)
          LAST_TAG=$(echo "$LAST_TAG" | tr -d '\r' | sed 's/[[:space:]]*$//')
          echo "Last Tag: $LAST_TAG"
          if [[ $LAST_TAG == "" ]]; then
            MINOR=0
          else
            MINOR=$(echo $LAST_TAG | awk -F '.' '{print $NF}')
            echo "Minor Version: $MINOR"
            MINOR=$((MINOR + 1))
          fi
          TAG="v$YEAR.$WEEK.$MINOR"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "Next Tag: $TAG"
      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Create and push tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$TAG" \
              --repo="$GITHUB_REPOSITORY" \
              --title="$TAG" \
              --generate-notes


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker buildx build \
            --file Dockerfile \
            --tag ghcr.io/eximpe/action-runner:latest \
            --tag ghcr.io/eximpe/action-runner:$TAG \
            --tag docker.io/eximpe/action-runner:latest \
            --tag docker.io/eximpe/action-runner:$TAG .

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Push image to GitHub Container Registry
        run: |
          docker push ghcr.io/eximpe/action-runner:latest
          docker push ghcr.io/eximpe/action-runner:$TAG

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        run: |
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:latest
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:$TAG

